# Generated by Django 5.2 on 2025-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capital', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(max_length=30)),
                ('subregion', models.CharField(blank=True, max_length=40, null=True)),
                ('population', models.PositiveBigIntegerField()),
            ],
        ),
    ]
